### ISSUE TITLE
[Feature Request] Add support for configuring camera and GPU memory

### ISSUE THREAD

**Issue by mfreeborn** [aniongithub/pi-bootstrap#7]
My use case involves setting up multiple Raspberry Pis which all act as remote cameras. It would be great to use this repo as starting point for building a generic fresh install. In order to do so, it would need to support enabling the camera (it is disabled by default) and customising the GPU memory.

Would it be simple to support this?

**Comment by aniongithub** [comment]
Thanks for the suggestion - I pushed feature branch and have a manual run going [here](https://github.com/aniongithub/pi-bootstrap/actions/runs/769380120). Since this is something that raspi-config supports, I'm ok for it to be a part of this repo.

Also, note that this repo. is not meant for generic fresh installs + manual software on top of it. Instead, it's meant as a starting point for users to add in any software they need. For example in your case, you'd have a private/public repo (derived from this template) where you'd edit `bootstrap/02-run.sh` to add in the remote camera software too in place of the docker installation. Hope that helps!

**Comment by aniongithub** [comment]
Camera and GPU memory support is now enabled. Set ENABLE_CAMERA=1 and GPU_MEM=128 (If you omit setting this, it will be set to 128. You can also request more memory for the GPU if you'd like).
